import React, { useCallback, useState } from "react";
import { View, Text, StyleSheet, FlatList, ActivityIndicator, TouchableOpacity } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { COLORS, SPACE, TYPE } from "../../constants/theme";
import { currentMonth } from "../../lib/dates";
import { MonthPicker } from "../../components/MonthPicker";
import { api } from "../../lib/api";
import { Card } from "../../components/FinanceUI";

export default function Expense() {
  const [month, setMonth] = useState(currentMonth); const router = useRouter(); const [items, setItems] = useState<any[]>([]); const [filters, setFilters] = useState<string[]>(["ทั้งหมด"]); const [filter, setFilter] = useState("ทั้งหมด"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); setError(null); const params: Record<string, string> = { month }; if (filter !== "ทั้งหมด") params.category = filter; const [rows, categories] = await Promise.all([api.getExpenses(params), api.getCategories("expense")]); setItems(rows); setFilters(["ทั้งหมด", ...new Set(categories.map(c => c.name))]); } catch (e: any) { setError(e.message); } finally { setLoading(false); } }, [filter, month]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  async function remove(id: string) { try { await api.deleteExpense(id); await load(); } catch (e: any) { setError(e.message); } }
  const total = items.reduce((sum, i) => sum + Number(i.amount || 0), 0);
  return <View style={s.wrap}><View style={s.header}><View><Text style={s.eyebrow}>รายการเงิน</Text><Text style={s.title}>รายจ่าย</Text></View><TouchableOpacity style={s.add} onPress={() => router.push("/expense-add")}><Text style={s.addText}>＋ เพิ่ม</Text></TouchableOpacity></View><MonthPicker month={month} onChange={setMonth} /><View style={s.filters}>{filters.map(f => <TouchableOpacity key={f} style={[s.filter, f === filter && s.filterActive]} onPress={() => setFilter(f)}><Text style={[s.filterText, f === filter && s.filterActiveText]}>{f}</Text></TouchableOpacity>)}</View><Card style={s.totalCard}><Text style={s.totalLabel}>รายจ่ายรวมเดือนนี้</Text><Text style={s.total}>฿{total.toLocaleString("th-TH")}</Text><Text style={s.totalHint}>{items.length} รายการ</Text></Card>{loading ? <ActivityIndicator style={{ marginTop: SPACE.xl }} color={COLORS.greenDk} /> : error ? <Text style={s.error}>{error}</Text> : <FlatList contentContainerStyle={s.list} data={items} keyExtractor={i => String(i.id)} ListEmptyComponent={<Text style={s.empty}>ยังไม่มีรายการรายจ่ายในเดือนนี้</Text>} renderItem={({ item }) => <Card style={s.item}><View><Text style={s.itemTitle}>{item.category}</Text><Text style={s.muted}>{item.note || "ไม่มีรายละเอียด"} · {item.date}</Text></View><View style={s.itemRight}><Text style={s.amount}>-฿{Number(item.amount).toLocaleString("th-TH")}</Text><TouchableOpacity onPress={() => remove(item.id)}><Text style={s.delete}>ลบ</Text></TouchableOpacity></View></Card>} />}</View>;
}
const s = StyleSheet.create({ wrap: { flex: 1, width: "100%", maxWidth: 1120, alignSelf: "center", backgroundColor: COLORS.bg, paddingHorizontal: SPACE.lg }, header: { paddingTop: 32, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { ...TYPE.caption, color: COLORS.text2 }, title: { ...TYPE.title, color: COLORS.text }, add: { backgroundColor: COLORS.greenDk, borderRadius: 999, paddingHorizontal: 16, paddingVertical: 10 }, addText: { color: COLORS.white, fontWeight: "800" }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: SPACE.md }, filter: { borderWidth: 1, borderColor: COLORS.line, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, backgroundColor: COLORS.card }, filterActive: { backgroundColor: COLORS.greenDk, borderColor: COLORS.greenDk }, filterText: { ...TYPE.caption, color: COLORS.text2 }, filterActiveText: { color: COLORS.white, fontWeight: "800" }, totalCard: { backgroundColor: COLORS.dangerBg, padding: SPACE.lg, marginBottom: SPACE.lg }, totalLabel: { ...TYPE.caption, color: COLORS.red }, total: { color: COLORS.red, fontSize: 28, fontWeight: "800", marginTop: 4 }, totalHint: { ...TYPE.caption, color: COLORS.text2, marginTop: 4 }, list: { paddingBottom: 100 }, item: { padding: SPACE.lg, marginBottom: SPACE.sm, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, itemTitle: { ...TYPE.body, fontWeight: "800", color: COLORS.text }, muted: { ...TYPE.caption, color: COLORS.text2, marginTop: 3, maxWidth: 230 }, itemRight: { alignItems: "flex-end", gap: 5 }, amount: { color: COLORS.danger, fontWeight: "800" }, delete: { color: COLORS.danger, ...TYPE.caption }, empty: { color: COLORS.text2, textAlign: "center", marginTop: SPACE.xl }, error: { color: COLORS.danger, textAlign: "center", marginTop: SPACE.xl } });
